spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:blog
    username: sa
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    com.hyp.learn: debug

server:
  port: 8010
